version: "3.3"
services:
  parity:
    build: parity
    ports:
      - "8545:8545"
  bridge-contracts:
    build: .
    command: "true"
    env_file: ./deploy/.env
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24